### ISSUE TITLE
selenium-wire >=4 breaks with pytest-asyncio

### ISSUE THREAD

**Issue by rra** [wkeeling/selenium-wire#209]
It looks like selenium-wire 4.0.0 or later (tested with 4.0.0 and 4.0.2) breaks when used with pytest-asyncio in an async test, apparently because there's some conflict over the running loops.

To reproduce, run `pip install selenium-wire pytest-asyncio` in a new virtual env, and then run `pytest` on the following test file:

```python
import pytest
from seleniumwire import webdriver


@pytest.fixture
def driver():
    options = webdriver.ChromeOptions()
    options.add_argument("headless")
    options.add_argument("no-sandbox")
    options.add_argument("disable-extensions")
    options.add_argument("incognito")
    driver = webdriver.Chrome(options=options)
    try:
        yield driver
    finally:
        driver.quit()


@pytest.mark.asyncio
async def test_selenium(driver) -> None:
    driver.get("https://www.google.com/")
```

I get the following output

```
============================= test session starts ==============================
platform linux -- Python 3.9.1+, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/eagle/tmp
plugins: asyncio-0.14.0
collected 1 item                                                               

test_selenium.py FException in thread Selenium Wire Proxy Server:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
E                                                      [100%]    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eagle/dvl/venvs/selenium/lib/python3.9/site-packages/seleniumwire/server.py", line 86, in serve_forever
    self._master.run_loop(self._event_loop.run_forever)

  File "/home/eagle/dvl/venvs/selenium/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/master.py", line 84, in run_loop

==================================== ERRORS ====================================
______________________ ERROR at teardown of test_selenium ______________________

    loop = asyncio.get_event_loop()
request = <SubRequest 'event_loop' for <Function test_selenium>>
  File "/usr/lib/python3.9/asyncio/events.py", line 642, in get_event_loop

    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Selenium Wire Proxy Server'.
    @pytest.fixture
    def event_loop(request):
        """Create an instance of the default event loop for each test case."""
        loop = asyncio.get_event_loop_policy().new_event_loop()
        yield loop
>       loop.close()

../dvl/venvs/selenium/lib/python3.9/site-packages/pytest_asyncio/plugin.py:210: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.9/asyncio/unix_events.py:58: in close
    super().close()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_UnixSelectorEventLoop running=False closed=False debug=False>

    def close(self):
        if self.is_running():
>           raise RuntimeError("Cannot close a running event loop")
E           RuntimeError: Cannot close a running event loop

/usr/lib/python3.9/asyncio/selector_events.py:89: RuntimeError
---------------------------- Captured log teardown -----------------------------
WARNING  urllib3.connectionpool:connectionpool.py:304 Connection pool is full, discarding connection: 127.0.0.1
=================================== FAILURES ===================================
________________________________ test_selenium _________________________________

kwargs = {'driver': <seleniumwire.webdriver.Chrome (session="cc8ada3562d7d6b901fd27ec469845ba")>}
coro = <coroutine object test_selenium at 0x7f59a0916b40>
task = <Task pending name='Task-2' coro=<test_selenium() running at /home/eagle/tmp/test_selenium.py:23>>

    @functools.wraps(func)
    def inner(**kwargs):
        coro = func(**kwargs)
        if coro is not None:
            task = asyncio.ensure_future(coro, loop=_loop)
            try:
>               _loop.run_until_complete(task)

../dvl/venvs/selenium/lib/python3.9/site-packages/pytest_asyncio/plugin.py:179: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.9/asyncio/base_events.py:618: in run_until_complete
    self._check_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_UnixSelectorEventLoop running=True closed=False debug=False>

    def _check_running(self):
        if self.is_running():
>           raise RuntimeError('This event loop is already running')
E           RuntimeError: This event loop is already running

/usr/lib/python3.9/asyncio/base_events.py:578: RuntimeError
=========================== short test summary info ============================
FAILED test_selenium.py::test_selenium - RuntimeError: This event loop is alr...
ERROR test_selenium.py::test_selenium - RuntimeError: Cannot close a running ...
========================== 1 failed, 1 error in 1.60s ==========================
```

Running `pip install 'selenium-wire<4'` and then re-running the test shows no errors.

**Comment by wkeeling** [comment]
Thanks for the detailed issue. I'll reproduce and look at getting a fix in. Many thanks.

**Comment by necuk** [comment]
hey same error when using latest selenium-wire version with jupyter notebook
after downgrading to 3.0.6 the problem is gone

code to reproduce

```
from seleniumwire import webdriver
driver = webdriver.Chrome()
```

traceback
```
Exception in thread Selenium Wire Proxy Server:
Traceback (most recent call last):
  File "\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "\anaconda3\lib\site-packages\seleniumwire\server.py", line 86, in serve_forever
    self._master.run_loop(self._event_loop.run_forever)
  File "\anaconda3\lib\site-packages\seleniumwire\thirdparty\mitmproxy\master.py", line 88, in run_loop
    loop.close()
  File "\anaconda3\lib\asyncio\selector_events.py", line 89, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
```
packet versions

```
jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.19.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.6
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 5.0.5
```

chrome version 88.0, tested on windows 10

**Comment by kilotone** [comment]
I noticed 3.9 is not supported on selenium-wire, I too hit the same error when using the driver.request_interceptor
I was adding request headers, but was already within a thread spawned with concurrent.futures.ThreadPoolExecutor

At the end of the loop, I attempted to .close() and .quit() the chromeDriver to no avail, producing the above referenced errors as well. I in addition am traversing File "/usr/lib/python3.9/asyncio/unix_events.py", line 58, in close prior to selector_events.py

**Comment by rra** [comment]
Oh, good catch, I should have mentioned that I am using Python 3.9, in case that's a factor here.

**Comment by kilotone** [comment]
This was relevant for me. https://idolstarastronomer.com/two-futures.html

**Comment by wkeeling** [comment]
These issues with the event loop should be fixed in v4.0.4. If you get a chance to confirm from your side I'd appreciate it. Thanks!

**Comment by necuk** [comment]
thanks it works well with jupyter notebook

**Comment by rra** [comment]
This is definitely better and it passes my minimal test. I'm still getting the following error with https://github.com/lsst-sqre/gafaelfawr (the `tests/selenium/tokens_test.py` test):

```
Test session starts (platform: linux, Python 3.9.1, pytest 6.2.2, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /home/eagle/lsst/gafaelfawr
plugins: sugar-0.9.4, httpx-0.10.1, asyncio-0.14.0, forked-1.3.0, xdist-2.2.0, cov-2.11.1
collecting ... 
 tests/selenium/tokens_test.py::test_create_token ✓              100% ██████████

Results (3.85s):
       1 passed
INFO:     Shutting down
Exception in thread Selenium Wire Proxy Server:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eagle/dvl/venvs/gafaelfawr/lib/python3.9/site-packages/seleniumwire/server.py", line 72, in serve_forever
    self._master.run()
  File "/home/eagle/dvl/venvs/gafaelfawr/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/master.py", line 99, in run
    self.run_loop(loop.run_forever)
  File "/home/eagle/dvl/venvs/gafaelfawr/lib/python3.9/site-packages/seleniumwire/thirdparty/mitmproxy/master.py", line 86, in run_loop
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Selenium Wire Proxy Server'.
```
Currently trying to figure out why and make a reduced test case for this, but it's only happening after the test runs and doesn't seem to prevent it from passing.

**Comment by rra** [comment]
Here's a new minimal test case that shows the above issue. It appears to be caused by a combination of having another async fixture and running selenium-wire with session scope. (You'll need to install aiohttp in the virtual env to run this test case; that was the thing I had on hand that made sense as an async fixture.) Removing the session scope makes the problem go away.

```python
import aiohttp
import pytest
from seleniumwire import webdriver


@pytest.fixture(scope="session")
def driver():
    options = webdriver.ChromeOptions()
    options.add_argument("headless")
    options.add_argument("no-sandbox")
    options.add_argument("disable-extensions")
    options.add_argument("incognito")
    driver = webdriver.Chrome(options=options)
    try:
        yield driver
    finally:
        driver.quit()


@pytest.fixture
async def session():
    async with aiohttp.ClientSession() as session:
        yield session 


@pytest.mark.asyncio
async def test_selenium(driver, session) -> None:
    driver.get("https://www.google.com/")
```

**Comment by kilotone** [comment]
Looks good on my end, I just need to clean up a file descriptor limit now.

**Comment by wkeeling** [comment]
@rra there's a new version available (v4.1.0) that should fix the exception you're seeing at the end of the test run. Thank you for your minimal test case - that was very useful for debugging the issue.

**Comment by rra** [comment]
Confirmed. Everything looks great now -- thank you so much!
